### ISSUE TITLE
Genesis of Musicoin testnet

### ISSUE THREAD

**Issue by pan1907** [Musicoin/PM#1]

**Comment by cwlau** [comment]
It is setup with following steps/ config:

**in node 1:**
- install parity (https://ethcore.io/parity.html)
- create twp new accounts by repeating `parity account new`.
- Obtain the account address, put them into `genesis_author.json`
 (Pls check content of `genesis_parity.json` below)
- Also use one address in the following command as `--author`
`parity --identity node1 --datadir ~/.parity/node1 --chain ~/.parity/genesis_parity.json --author 0xb0395cbaa449e853601498009cb0fc23764e47c8`

`{
"name": "node 1",
"engine": {
"Ethash": {
"params": {
"gasLimitBoundDivisor": "0x0400",
"minimumDifficulty": "0x020000",
"difficultyBoundDivisor": "0x0800",
"durationLimit": "0x0a",
"blockReward": "0x4563918244F40000",
"registrar": "",
"frontierCompatibilityModeLimit": "0x0"
}
}
},
"params": {
"accountStartNonce": "0x0100000",
"maximumExtraDataSize": "0x20",
"minGasLimit": "0x1388",
"networkID" : "0x100"
},
"genesis": {
"seal": {
"ethereum": {
"nonce": "0x00006d6f7264656e",
"mixHash": "0x00000000000000000000000000000000000000647572616c65787365646c6578"
}
},
"difficulty": "0x20000",
"author": "0x0000000000000000000000000000000000000000",
"timestamp": "0x00",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"extraData": "0x",
"gasLimit": "0x2fefd8"
},
"nodes": [
],
"accounts": {
"ac4a6cf67ee348fcf5d41448b007e87681d57aaa": { "balance": "999999", "nonce": "1048576" },
"497c762869459b333d4f0accad589ce364429470": { "balance": "999999", "nonce": "1048576" },
"bc3bb8b1ae2097e55f250153ec2ccfa187ca20c7": { "balance": "999999", "nonce": "1048576" },
"67da14b3f41e316f7c14ed96b9a7df385ee2e174": { "balance": "999999", "nonce": "1048576" },
"14183b0c874bd88fce3865304b38b1ef4310a2d2": { "balance": "999999", "nonce": "1048576" },
"7ae9dc4389e976234a45ecacf9cacd9d8a37df66": { "balance": "999999", "nonce": "1048576" },
"bd00b887914c50055536b257d54c62a8309d6ee9": { "balance": "999999", "nonce": "1048576" },
"c896e915bb5db301a7732036918e4cf3fc3d1d53": { "balance": "999999", "nonce": "1048576" },
"6efdc4e23c952f79cc18eb2d446fe203ae070ae8": { "balance": "999999", "nonce": "1048576" },
"d7c7759f7d3a5099499529ab1380774d5a502be8": { "balance": "999999", "nonce": "1048576" },
"b0395cbaa449e853601498009cb0fc23764e47c8": { "balance": "999999", "nonce": "1048576" }
}
}`


**in node 2:**
- Make a copy of `genesis_parity.json` as `genesis_parity2.json`, modify the `nodes` session to include a string `"enode://c1f83ed6cf703cb6bb8205b59b28b23e8a05a9c00a8458885b9f0a77b9dc5103599c0366c6e535400529b372fa68d880218b2ac291253248d1005c4593978320@104.154.22.12:30303"`. This URI can be obtained when there is no `--nodiscover` flag enabled.
- `parity --identity node2 --datadir ~/.parity/node2 --jsonrpc-port 8902 --port 30802 --no-dapps --signer-port 8181 --chain ~/.parity/genesis_parity2.json --author 0xc896e915bb5db301a7732036918e4cf3fc3d1d53`
The second node should be able to connect to the first one.


_A note from Dan_
`parity --dapps-port 8081 --chain "~\private-net\chain\private-chain.json" --datadir "~\private-net\db" --keys-path "~\private-net\keys" --signer-path "~\private-net\signer" --no-import-keys --geth` and  `--no-import-keys` will prevent parity from pulling keys from the normal directory.

**Comment by immartian** [comment]
I met some issues running up:

Starting Parity/v1.3.1-beta/x86_64-linux-gnu/rustc1.11.0
2016-09-29 15:53:18 Using state DB journalling strategy fast
2016-09-29 15:53:18 Import geth accounts failed. Invalid key file: "/home/im/.ethereum/keystore/UTC--2016-05-24T06-19-40.415170200Z--00756cf8159095948496617f5fb17ed95059f536": Invalid hash at line 1 column 164
2016-09-29 15:53:18 Configured for node 1 using Ethash engine
2016-09-29 15:53:18 Error starting network: StdIo(Error { repr: Os { code: 98, message: "Address already in use" } })
WebApps io error: Address already in use (os error 98)

Why Parity still trying to get from Ethereum installed in same machine?

**Comment by immartian** [comment]
resolved, by adding   --no-dapps

**Comment by cwlau** [comment]
Updated above comment by adding `--no-dapps` flag.

**Comment by immartian** [comment]
There's still problems running contract code on private chain, as @phiferd found, especially on functions returning string value.

**Comment by phiferd** [comment]
the issue regarding string returns was resolved by updating the config to include the (apparently required) builtin accounts.  I verified by starting several local chains with and without the builtin accounts.
