### ISSUE TITLE
Define the structure of License

### ISSUE THREAD

**Issue by pan1907** [Musicoin/PM#13]
Based on discussion: https://musicoin.slack.com/archives/core/p1475656545001127

**Comment by pan1907** [comment]
@immartian designed the structure and shared on whiteboard today. See #26

**Comment by pan1907** [comment]
@cwlau and @Hibryda prepared two versions. Team will decide to adopt one to proceed. 

@cwlau (more info in #26  ): https://docs.google.com/document/d/1SVUq9Xqe5yevKD0R2imbpCrhxt0q8vTCGWaGQZCQgA0/edit

@Hibryda : https://docs.google.com/spreadsheets/d/16oIB-Tip-iUiaU-axbRayyYncKzF_hbAMQTX6WnfxHg/edit#gid=0

**Comment by immartian** [comment]
To me, readable contract/license is also important rather than make them granite. Please let's keep all the task running before it's getting over-dued.

**Comment by Hibryda** [comment]
Readability is assured by app, so there is not much difference if we feed it with text or opcodes. Actually, the only issue is that opcodes filter way better than text (SQL injection analogy)

**Comment by pan1907** [comment]
Go with JSON as proposed in #26 for MVP2. Closing the issue.
