### ISSUE TITLE
Musicoin homepage v0.2

### ISSUE THREAD

**Issue by pan1907** [Musicoin/PM#22]
Design and implement

**Comment by immartian** [comment]
I have changed the title to v0.2

**Comment by immartian** [comment]
https://www.figma.com/file/e25GgztFCnIvw2YxdYBCUK8n/Musicoin-whole-board  the structure will refer to this wire-frame but content need to be fully enriched.

**Comment by immartian** [comment]
As William's mom in hospital, I wonder it's delay upcoming.

**Comment by immartian** [comment]
let's put "Every play is born to be equal" at the center position.

**Comment by immartian** [comment]
adding some words to "How it works" wiki page. Please help update.

**Comment by cwlau** [comment]
Updated site "How it works" to revision 5. (11efe11)
https://github.com/Musicoin/musicoin/wiki/How-It-Work%3F
