### ISSUE TITLE
ffmpeg: No sound play under Mac OS

### ISSUE THREAD

**Issue by pan1907** [Musicoin/PM#47]

**Comment by phiferd** [comment]
I do not have access to a Mac, so I don't think I will be able to troubleshoot this.

**Comment by pan1907** [comment]
@phiferd no problem.

**Comment by immartian** [comment]
we have spare Mac at office, maybe we can send you one to test.

**Comment by phiferd** [comment]
ok.  that would work.

**Comment by pan1907** [comment]
Fixed by @phiferd with packaging nwjs in Mac OS.

**Comment by immartian** [comment]
Thanks. This is great!
