### ISSUE TITLE
Media player

### ISSUE THREAD

**Issue by pan1907** [Musicoin/PM#5]

**Comment by immartian** [comment]
it's finished at @phiferd 's repo, can you move to our test repo, Dan?  I have some bugs to report.

**Comment by immartian** [comment]
E.g. on Ubuntu, the player can't be played with following errors:

> [24349:24349:1004/205609:ERROR:render_media_log.cc(25)] MediaEvent: PIPELINE_ERROR demuxer: could not open
> 
> chrome-extension://dodonagcbffonieibfhaicolhgmndpao/bower_components/paper-audio-player/paper-audio-player.html:337
>         e.preventDefault();
>          ^
> 
> TypeError: Cannot read property 'preventDefault' of undefined
>     at paper-audio-player.restart (chrome-extension://dodonagcbffonieibfhaicolhgmndpao/bower_components/paper-audio-player/paper-audio-player.html:337:10)
>     at playAudioAtUrl (chrome-extension://dodonagcbffonieibfhaicolhgmndpao/src/my-player-view.html:299:20)
>     at Object.onPaymentInitiated (chrome-extension://dodonagcbffonieibfhaicolhgmndpao/src/my-player-view.html:262:25)
>     at Object.callback (chrome-extension://dodonagcbffonieibfhaicolhgmndpao/src/my-player-view.html:315:30)
> 
> [24349:24349:1004/205648:ERROR:render_media_log.cc(25)] MediaEvent: PIPELINE_ERROR demuxer: could not open
>

**Comment by phiferd** [comment]
Yes, I can move to the musicoin repo tomorrow.  

I think the issue above is related to a fix that I've made in the paper audio player that isn't captured in the github repo.  William should be able to help you get past that until we sort out the right solution.  At this point, I'm not really using paper audio player, so I could switch back to the standard HTML5 player.  The issue with paper audio player was that it was not design to be controlled programmatically and assumes that each start/stop will be triggered directly by a user input event (click).
