### ISSUE TITLE
Musician profile - Tip

### ISSUE THREAD

**Issue by pan1907** [Musicoin/PM#62]
If click “Tip” button, trigger tipping process and send one tip to the musician from this user

**Comment by phiferd** [comment]
What address does the tip go to?  Will there be a musician profile API?

**Comment by pan1907** [comment]
Goes to the address the musician is binded with. @cwlau would you please comment on the API question? thanks.

**Comment by immartian** [comment]
Yes, we need this, even a stub. 
Based on this, we can extend a feature to show artist's avatar along with music.  like this 

![image](https://cloud.githubusercontent.com/assets/81030/19712245/cf79eb42-9b6e-11e6-8054-097d05dd510d.png)

**Comment by cwlau** [comment]
Just made http://catalog.musicoin.org/api/musician/content?address=0xd9b87b28449de9a45560fadace31300fcc50e68b as a stub.  
`address` is required but it can be any value for now.

**Comment by phiferd** [comment]
ok, but the address I send in -- is that the owner address of the work?  Probably good enough for now, but I'm not sure the relationship between the account that publishes the work and the "artist" will be so simple.
