### ISSUE TITLE
Wallet - transaction history

### ISSUE THREAD

**Issue by pan1907** [Musicoin/PM#70]
Click “History” button, display transaction history of this address (order by date, latest on top)

**Comment by phiferd** [comment]
Will this be backed by a service API?

**Comment by pan1907** [comment]
@cwlau would you please confirm? thanks.

**Comment by cwlau** [comment]
There is no plan for this API yet.  Client may need to query from blockchain for the info.

**Comment by phiferd** [comment]
For PPP and tips that are sent to a PPP contract, this is done.  Monitoring all transactions (i.e. and amount sent or received) is more of a pain because it's very CPU intensive to scan the logs.
