### ISSUE TITLE
A working site of blockchain explorer

### ISSUE THREAD

**Issue by immartian** [Musicoin/PM#86]
also link to a subdomain

**Comment by immartian** [comment]
finally a big issue was solved by Parity team member, together with me. https://github.com/keorn/parity-spec/issues/5#issuecomment-262286450  the next move could be faster, hopefully.

**Comment by immartian** [comment]
http://104.198.101.250:3000/ roughly running up at this address, still many internal bugs and data integrity issues, adding continuous crash with Parity db.

**Comment by immartian** [comment]
![image](https://cloud.githubusercontent.com/assets/81030/20557578/fa8f257e-b1a6-11e6-8ccb-f13d28b16715.png)

the left part of statics, is definitely not accurate yet.

**Comment by immartian** [comment]
redefining DB structure to be more future-compatible, going to commit a release.

**Comment by immartian** [comment]
please help point orbiter.musicoin.org to 104.198.101.250  (served in Google Cloud as an instance), @cwlau , thanks.

**Comment by immartian** [comment]
@phiferd , please comment this MVP from your current needs, I will put new goals to next MVP.

**Comment by cwlau** [comment]
Updated DNS settings and now it works at http://orbiter.musicoin.org:3000/ . 👍

**Comment by immartian** [comment]
thanks!
