### ISSUE TITLE
Show the contract "layers"

### ISSUE THREAD

**Issue by immartian** [Musicoin/PM#87]
The three view design has been defined yet to be prototyped. 
https://github.com/Musicoin/musicoin/wiki/PPP-license-in-3-views

**Comment by phiferd** [comment]
The linked item is helpful, thanks.  Is there some text that I can copy/paste?

Also, do you think the license text should be stored in the app?  Another option is to have a hosted version, which would allow you to update as needed.  e.g. a page that accepts a contract Id and a layer name, then renders as you have indicated.  

Alternately, the template could be stored at a URL, and I can pull and populate it in the client.  I could just cache the templates and then check for a new version on startup.  That way, it can be updated but the user could still view them even if they are offline.

**Comment by immartian** [comment]
I think a hosted version would be helpful someday, but temporarily we have to rely on client app a lot to include our concept and messages. This may be a temp solution to load from local. Thinking of the 3rd layer, smart contract, it's already in local(maybe same to put to cloud to upgrade time by time as well).

**Comment by phiferd** [comment]
Of course, there could also be a contract that holds links to the templates in IPFS, which would mean we don't need to have them hosted.  The contract could allow the owner (musicoin) to update the ipfs references when the contract is updated

**Comment by phiferd** [comment]
I don't currently have a way to resolve an address to a person's name.  It seems like we would need the registration flow to support this.

**Comment by immartian** [comment]
can we set locally first? e.g. make the user name part editable in profile page.

**Comment by phiferd** [comment]
it is editable now, but payments to other addresses (not the logged in user) will need to be resolved.  The names are not stored in the blockchain, so even if I can show names in the preview (before release), I won't be able to show them when you look at someone else's contract.

**Comment by phiferd** [comment]
Maybe the answer is to update the contract to store the names in the blockchain

**Comment by immartian** [comment]
I think the safest way is to display address this moment.

**Comment by phiferd** [comment]
ok. In any case the address will need to be displayed as that is the only guarantee we can actually give.  e.g. if "Joe Smith" is listed in the contract at 0x1111, and he loses his password and sets up a new account at 0x2222, the contract will still pay 0x1111.  This is different than a normal contract, where you would cut a check to Joe Smith and you don't really care what his account address is.

**Comment by immartian** [comment]
I think there will be some inclusiveness in catalog service part to display several current addresses including deprecated ones.

**Comment by phiferd** [comment]
ok.  for now I will show the addresses.  Let's open a separate issue to track resolving those addresses to names and consider corner cases (like the one I listed above).

**Comment by phiferd** [comment]
![image](https://cloud.githubusercontent.com/assets/25631/20384032/27c7071e-aced-11e6-987f-8fe07b4e611a.png)

A preview of the PPP human readable license in the new release flow.  I will change the "Release" button to say "Preview License", and then show this in a dialog.  The dialog will have the "Release" button inside.

**Comment by phiferd** [comment]
@immartian  If you have some legalese for the other layer, please attach it to this issue

**Comment by immartian** [comment]
I can hardly provide a lawyer reviewed document, will give a draft, though.

**Comment by immartian** [comment]
for the preview, do you think it's possible to be thumbnail and click to expand full content?

**Comment by phiferd** [comment]
Additional details in #95

**Comment by phiferd** [comment]
updated to show all three versions of the license.

![image](https://cloud.githubusercontent.com/assets/25631/20557113/0b118876-b1a5-11e6-90b1-120c87a78df8.png)
