### ISSUE TITLE
Playlist UX

### ISSUE THREAD

**Issue by phiferd** [Musicoin/PM#90]
> The playlist/music works and release display should be different in visual

@immartian please clarify.

**Comment by phiferd** [comment]
Updated UX for playlists in https://github.com/Musicoin/desktop/commit/b23b17472e2c66f54ad36e242742f260cda6eaad

![image](https://cloud.githubusercontent.com/assets/25631/20482910/4bfdc696-b02a-11e6-940b-693b72282bb3.png)

**Comment by immartian** [comment]
pretty cool
